# Shared helpers for the portable Proxmox lab. Dot-source this file.
$ProxmoxRoot = $PSScriptRoot
$CacheDir = Join-Path $ProxmoxRoot ".cache"
$KeysDir = Join-Path $ProxmoxRoot "keys"
$WslDir = Join-Path $ProxmoxRoot "wsl"
$SecretsPath = Join-Path $ProxmoxRoot "secrets.env"

$VmName = "Proxmox"
$IsoName = "proxmox-ve_9.2-1.iso"
$IsoUrl = "https://enterprise.proxmox.com/iso/proxmox-ve_9.2-1.iso"
$IsoSha256 = "4e88fe416df9b527624a175f24c9aa07c714d3332afb1ee3dbf3879573ef2c6c"
$AutoIsoName = "proxmox-ve_9.2-1-auto.iso"
$DiskName = "pve.vhdx"
$DiskGb = 64
$MemoryMb = 4096
$VCpus = 4
$SshPort = 2222
$WebPort = 8006
$VncDisplay = 1
$Fqdn = "pve.lab.local"
$WslDistro = "Ubuntu-24.04"

function ConvertTo-WslPath([string]$WindowsPath) {
    $p = $WindowsPath -replace '\\', '/'
    if ($p -match '^([A-Za-z]):(.*)$') {
        return "/mnt/$($Matches[1].ToLower())$($Matches[2])"
    }
    return $p
}

function Invoke-PveWsl {
    param(
        [string]$Command,
        [string]$User = "root",
        [switch]$IgnoreExit
    )
    $output = & wsl.exe -d $WslDistro -u $User -- bash -lc $Command 2>&1
    $code = $LASTEXITCODE
    if ($output) { $output | ForEach-Object { Write-Host $_ } }
    if (-not $IgnoreExit -and $code -ne 0) {
        throw "WSL command failed (exit $code): $Command"
    }
    return $code
}

function Test-HyperVAvailable {
    return [bool](Get-Command New-VM -ErrorAction SilentlyContinue)
}

function Get-ProxmoxDrive {
    if ($env:PROXMOX_DRIVE) {
        return $env:PROXMOX_DRIVE.TrimEnd('\')
    }

    $labeled = Get-Volume -ErrorAction SilentlyContinue |
        Where-Object { $_.DriveLetter -and $_.FileSystemLabel -in @('PROXMOX', 'PVE', 'PVE-USB') } |
        Select-Object -First 1
    if ($labeled) { return "$($labeled.DriveLetter):" }

    $p = Get-Volume -DriveLetter P -ErrorAction SilentlyContinue
    if ($p -and $p.FileSystem) { return "P:" }

    $usbDisks = Get-Disk -ErrorAction SilentlyContinue | Where-Object {
        -not $_.IsBoot -and -not $_.IsSystem -and (
            $_.BusType -eq 'USB' -or
            $_.FriendlyName -match 'NS-PCNVME|Best Buy|USB|External|NVMe'
        )
    }
    foreach ($disk in $usbDisks) {
        $part = Get-Partition -DiskNumber $disk.Number -ErrorAction SilentlyContinue |
            Where-Object { $_.DriveLetter } |
            Select-Object -First 1
        if ($part) { return "$($part.DriveLetter):" }
    }
    return $null
}

function Wait-ProxmoxDrive {
    param([int]$TimeoutSeconds = 180)
    $sw = [Diagnostics.Stopwatch]::StartNew()
    while ($sw.Elapsed.TotalSeconds -lt $TimeoutSeconds) {
        $drive = Get-ProxmoxDrive
        if ($drive) { return $drive }
        Write-Host "Waiting for USB-C NVMe (NTFS, label PROXMOX, or drive P:)... $($sw.Elapsed.ToString('mm\:ss'))"
        Start-Sleep -Seconds 5
    }
    return $null
}

function Get-ProxmoxDataDir {
    param([switch]$Wait)
    $drive = if ($Wait) { Wait-ProxmoxDrive } else { Get-ProxmoxDrive }
    if (-not $drive) { return $null }
    return Join-Path $drive "proxmox"
}

function Get-SecretMap {
    $map = @{}
    if (Test-Path $SecretsPath) {
        Get-Content $SecretsPath | ForEach-Object {
            if ($_ -match '^\s*#' -or $_ -notmatch '=') { return }
            $k, $v = $_.Split('=', 2)
            $map[$k.Trim()] = $v.Trim()
        }
    }
    return $map
}

function Initialize-ProxmoxSecrets {
    New-Item -ItemType Directory -Force -Path $CacheDir, $KeysDir | Out-Null
    $key = Join-Path $KeysDir "id_ed25519"
    if (-not (Test-Path $key)) {
        & ssh-keygen -t ed25519 -f $key -N "" -C "pve-portable@wsl"
    }

    $secrets = Get-SecretMap
    if (-not $secrets.ContainsKey('PVE_ROOT_PASSWORD')) {
        $chars = [char[]](([char]'A'..[char]'Z') + ([char]'a'..[char]'z') + ([char]'0'..[char]'9'))
        $rng = [Security.Cryptography.RandomNumberGenerator]::Create()
        $bytes = New-Object byte[] 16
        $rng.GetBytes($bytes)
        $password = -join ($bytes | ForEach-Object { $chars[$_ % $chars.Length] })
        @(
            "# Generated by scripts/proxmox. Do not commit."
            "PVE_ROOT_PASSWORD=$password"
        ) | Set-Content -Encoding ascii $SecretsPath
        $secrets = Get-SecretMap
        Write-Host "Wrote root password to $SecretsPath"
    }
    return $secrets
}

function New-ProxmoxAnswerFile {
    $secrets = Initialize-ProxmoxSecrets
    $pub = (Get-Content (Join-Path $KeysDir "id_ed25519.pub") -Raw).Trim()
    $pass = $secrets['PVE_ROOT_PASSWORD']
    $hash = & wsl.exe -d $WslDistro -u root -- openssl passwd -6 $pass
    $hash = ($hash | Out-String).Trim()
    if (-not $hash.StartsWith('$6$')) {
        throw "Failed to hash root password with openssl"
    }

    $template = Get-Content (Join-Path $ProxmoxRoot "answer.toml.template") -Raw
    $answer = $template.Replace('{{ROOT_PASSWORD_HASH}}', $hash).Replace('{{SSH_PUBKEY}}', $pub).Replace('{{FQDN}}', $Fqdn)
    $out = Join-Path $CacheDir "answer.toml"
    $utf8 = New-Object System.Text.UTF8Encoding $false
    [IO.File]::WriteAllText($out, $answer, $utf8)
    return $out
}

function Ensure-ProxmoxIso {
    $iso = Join-Path $CacheDir $IsoName
    if (Test-Path $iso) {
        $len = (Get-Item $iso).Length
        if ($len -gt 1GB) { return $iso }
    }
    New-Item -ItemType Directory -Force -Path $CacheDir | Out-Null
    $wslDir = ConvertTo-WslPath $CacheDir
    Write-Host "Downloading $IsoName..."
    Invoke-PveWsl "mkdir -p '$wslDir' && cd '$wslDir' && wget -c --progress=dot:giga '$IsoUrl'"
    return $iso
}

function Test-IsoChecksum([string]$IsoPath) {
    $wslIso = ConvertTo-WslPath $IsoPath
    $got = & wsl.exe -d $WslDistro -u root -- sha256sum $wslIso
    $gotHash = ($got -split '\s+')[0]
    if ($gotHash -ne $IsoSha256) {
        throw "ISO checksum mismatch. expected $IsoSha256 got $gotHash"
    }
}
